Added change of default-browser to zen. Excluded AUR pakage install because it does not work properly.

diff --git a/.dotfiles/general.yml b/.dotfiles/general.yml
--- a/.dotfiles/general.yml
+++ b/.dotfiles/general.yml
@@ -24,23 +24,27 @@
           - nextcloud-client
         state: present
       become: true
-    - name: Install packages from AUR
-      ansible.builtin.shell: |
-        packages=(
-            zen-browser-bin
-          )
-
-        rc=0
-        for p in "${packages[@]}"; do
-          if omarchy-pkg-missing $p; then
-            rc=254
-            omarchy-pkg-aur-add $p
-          fi
-        done
-        exit $rc
-      register: result
-      failed_when: result.rc != 0 and result.rc != 254
-      changed_when: result.rc == 254
+    # This works running interactively but fails in the playbook for some reason
+    # Install manually for now
+    # - name: Install packages from AUR
+    #   ansible.builtin.shell: |
+    #     packages=(
+    #         zen-browser-bin
+    #       )
+    #
+    #     rc=0
+    #     for p in "${packages[@]}"; do
+    #       if omarchy-pkg-missing $p; then
+    #         rc=254
+    #         omarchy-pkg-aur-add $p
+    #       fi
+    #     done
+    #     exit $rc
+    #   register: result
+    #   failed_when: result.rc != 0 and result.rc != 254
+    #   changed_when: result.rc == 254
+    # - debug:
+    #     msg: "{{ result.stdout }}"
     - name: Create folder for git repos
       ansible.builtin.file:
         name: "~/repos"
@@ -51,6 +55,17 @@
           exit 0
         else
           omarchy-theme-set "Ethereal"
+          exit 254
+        fi
+      register: result
+      failed_when: result.rc != 0 and result.rc != 254
+      changed_when: result.rc == 254
+    - name: Check and change current browser
+      ansible.builtin.shell: |
+        if [ $(xdg-settings get default-web-browser) = "zen.desktop" ]; then
+          exit 0
+        else
+          xdg-settings set default-web-browser zen.desktop
           exit 254
         fi
       register: result
